In [ ]:
!pip -q install rdkit
import pandas as pd
import numpy as np
from rdkit.Chem import PandasTools
from rdkit import Chem

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# HigDiv
HigDiv=pd.read_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/DOCK_HighDiv/DOCK_smHD8_HighDiv_Reps_Est.csv")
HigDiv

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,Score_mean,Score_std,Score_cv,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv
0,HD8_HD001,OC(=S)NC1=CC=C(C(=C1)/C=C/CC1=NC(=CN1)[C@H](C)...,C=Cc1ccc(NC(O)=S)cc1/C=C/Cc1nc([C@H](C)S)c[nH]1,smHD8_HighDiv,-6.44,-6.11,-5.82,-6.123333,0.310215,0.050661,23,-0.280000,-0.265652,-0.253043,-0.280000,0.000000e+00,0.000000e+00
1,HD8_HD002,OC1=CC=C(C(=C1)C1=CC(Cl)=CC(=C1O)Cl)CC(=O)C,CC(=O)Cc1ccc(O)cc1-c1cc(Cl)cc(Cl)c1O,smHD8_HighDiv,-5.47,-5.43,-5.46,-5.453333,0.020817,0.003817,20,-0.273500,-0.271500,-0.273000,-0.273500,0.000000e+00,0.000000e+00
2,HD8_HD003,OC(=O)C/C=C/C1=CNC(=NC1)C1=C(Br)C=NN1,O=C(O)C/C=C/C1=CNC(c2[nH]ncc2Br)=NC1,smHD8_HighDiv,-5.81,-5.84,-5.93,-5.860000,0.062450,0.010657,18,-0.322778,-0.324444,-0.329444,-0.322778,0.000000e+00,0.000000e+00
3,HD8_HD004,OC1=CC=C(C=C1)CC#CC1C(I)=CN=C(C=1Cl)N,Nc1ncc(I)c(C#CCc2ccc(O)cc2)c1Cl,smHD8_HighDiv,-5.52,-5.57,-5.50,-5.530000,0.036056,0.006520,19,-0.290526,-0.293158,-0.289474,-0.290526,0.000000e+00,0.000000e+00
4,HD8_HD005,OC1=CC=C(C=C1[C@H](CC1=CSN=C1)O)C(=C)C=C,C=CC(=C)c1ccc(O)c([C@@H](O)Cc2cnsc2)c1,smHD8_HighDiv,-6.15,-6.08,-5.96,-6.063333,0.096090,0.015848,19,-0.323684,-0.320000,-0.313684,-0.323684,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,HD8_HD326,O[C@](C)(C1=CCC=C1)C1=NN=C(S1)C(=O)[O-],C[C@@](O)(C1=CCC=C1)c1nnc(C(=O)O)s1,smHD8_HighDiv,-4.28,-4.32,-4.32,-4.306667,0.023094,0.005362,16,-0.267500,-0.270000,-0.270000,-0.267500,0.000000e+00,0.000000e+00
326,HD8_HD327,O[C@@H](CCl)C1=CON=C1O,Oc1nocc1[C@@H](O)CCl,smHD8_HighDiv,-4.28,-4.72,-4.03,-4.343333,0.349333,0.080430,10,-0.428000,-0.472000,-0.403000,-0.428000,6.798700e-17,1.588481e-16
327,HD8_HD328,OC1=CC=C(C=C1)C(=C)C(=O)C1=CNCS1,C=C(C(=O)C1=CNCS1)c1ccc(O)cc1,smHD8_HighDiv,-5.13,-5.09,-5.40,-5.206667,0.168622,0.032386,16,-0.320625,-0.318125,-0.337500,-0.320625,0.000000e+00,0.000000e+00
328,HD8_HD329,S[C@H](CC(=O)C1=CC(O)=C(C=C1Cl)O)C,C[C@H](S)CC(=O)c1cc(O)c(O)cc1Cl,smHD8_HighDiv,-4.79,-4.79,-4.62,-4.733333,0.098150,0.020736,15,-0.319333,-0.319333,-0.308000,-0.319333,0.000000e+00,0.000000e+00
329,HD8_HD330,O=C1NN=C(N1)C[C@@H](C1=CSC=N1)C=C,C=C[C@@H](Cc1n[nH]c(=O)[nH]1)c1cscn1,smHD8_HighDiv,-5.90,-5.47,-5.98,-5.783333,0.274287,0.047427,15,-0.393333,-0.364667,-0.398667,-0.393333,0.000000e+00,0.000000e+00

In [ ]:
#Druglike
Druglike=pd.read_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/DOCK_Druglike/DOCK_smHD8_DrugLike_Reps_Est.csv")
Druglike

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,Score_mean,Score_std,Score_cv,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv
0,HD8_DL001,OC(=O)C1C=CC=C2C=1N/C(=C/CC(=O)NCC1=CC=CC3=C1C...,O=C(C/C=C1\Cc2cccc(C(=O)O)c2N1)NCc1cccc2c1C(=O...,smHD8_Druglike,-6.50,-6.85,-6.63,-6.660000,0.176918,0.026564,29,-0.224138,-0.236207,-0.228621,-0.224138,0.0,0.0
1,HD8_DL002,ClC1=CC=C(C=C1)COCCNC(=O)C/C=C\1/NC2C(C1)=CC=C...,CCc1ccc2c(c1)N/C(=C/CC(=O)NCCOCc1ccc(Cl)cc1)C2,smHD8_Druglike,-6.46,-5.99,-6.34,-6.263333,0.244199,0.038989,27,-0.239259,-0.221852,-0.234815,-0.239259,0.0,0.0
2,HD8_DL003,C1C(OCC2=NC=CC(=C2)C(=O)N)=CC(=CC=1)N1C(=CCNC1...,NC(=O)c1ccnc(COc2cccc(N3CNCC=C3C(=O)O)c2)c1,smHD8_Druglike,-6.13,-5.48,-6.09,-5.900000,0.364280,0.061742,26,-0.235769,-0.210769,-0.234231,-0.235769,0.0,0.0
3,HD8_DL004,C1=NC2C(C(=O)O1)=CC=CC=2NC(=O)C/C=C\1/NC2C(C1)...,CCc1ccc2c(c1)N/C(=C/CC(=O)Nc1cccc3c(=O)ocnc13)C2,smHD8_Druglike,-6.97,-5.59,-5.70,-6.086667,0.766964,0.126007,27,-0.258148,-0.207037,-0.211111,-0.258148,0.0,0.0
4,HD8_DL005,OC(=O)C1C=CC=C2C=1N/C(=C/CC(=O)NC[C@@H](CO)F)/C2,O=C(C/C=C1\Cc2cccc(C(=O)O)c2N1)NC[C@H](F)CO,smHD8_Druglike,-5.03,-5.47,-5.41,-5.303333,0.238607,0.044992,22,-0.228636,-0.248636,-0.245909,-0.228636,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,HD8_DL287,OC(=O)C1=NN=C(O1)CC#CC(O)(F)F,O=C(O)c1nnc(CC#CC(O)(F)F)o1,smHD8_Druglike,-4.54,-4.37,-4.23,-4.380000,0.155242,0.035443,15,-0.302667,-0.291333,-0.282000,-0.302667,0.0,0.0
287,HD8_DL288,C(=C\CN)/C1=CC=C2C(=C1)C(=O)C=CN2,NC/C=C/c1ccc2[nH]ccc(=O)c2c1,smHD8_Druglike,-4.90,-4.99,-4.91,-4.933333,0.049329,0.009999,15,-0.326667,-0.332667,-0.327333,-0.326667,0.0,0.0
288,HD8_DL289,OC(=O)C/C=C/C1C=CC=C(C=1Cl)O,O=C(O)C/C=C/c1cccc(O)c1Cl,smHD8_Druglike,-4.05,-4.02,-4.05,-4.040000,0.017321,0.004287,14,-0.289286,-0.287143,-0.289286,-0.289286,0.0,0.0
289,HD8_DL290,OC(=O)/C=C/CCC1=NC2=C(N1)N=CC=C2,O=C(O)/C=C/CCc1nc2cccnc2[nH]1,smHD8_Druglike,-4.95,-4.98,-4.95,-4.960000,0.017321,0.003492,16,-0.309375,-0.311250,-0.309375,-0.309375,0.0,0.0
290,HD8_DL291,OC(=O)C1=NN=C(O1)C/C(=C/CC(=O)N)/C,C/C(=C\CC(N)=O)Cc1nnc(C(=O)O)o1,smHD8_Druglike,-4.67,-4.70,-4.78,-4.716667,0.056862,0.012056,16,-0.291875,-0.293750,-0.298750,-0.291875,0.0,0.0

In [ ]:
#Merging database
DB_DOCK_final = pd.concat([HigDiv, Druglike], ignore_index=True)
DB_DOCK_final

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,Score_mean,Score_std,Score_cv,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv
0,HD8_HD001,OC(=S)NC1=CC=C(C(=C1)/C=C/CC1=NC(=CN1)[C@H](C)...,C=Cc1ccc(NC(O)=S)cc1/C=C/Cc1nc([C@H](C)S)c[nH]1,smHD8_HighDiv,-6.44,-6.11,-5.82,-6.123333,0.310215,0.050661,23,-0.280000,-0.265652,-0.253043,-0.280000,0.0,0.0
1,HD8_HD002,OC1=CC=C(C(=C1)C1=CC(Cl)=CC(=C1O)Cl)CC(=O)C,CC(=O)Cc1ccc(O)cc1-c1cc(Cl)cc(Cl)c1O,smHD8_HighDiv,-5.47,-5.43,-5.46,-5.453333,0.020817,0.003817,20,-0.273500,-0.271500,-0.273000,-0.273500,0.0,0.0
2,HD8_HD003,OC(=O)C/C=C/C1=CNC(=NC1)C1=C(Br)C=NN1,O=C(O)C/C=C/C1=CNC(c2[nH]ncc2Br)=NC1,smHD8_HighDiv,-5.81,-5.84,-5.93,-5.860000,0.062450,0.010657,18,-0.322778,-0.324444,-0.329444,-0.322778,0.0,0.0
3,HD8_HD004,OC1=CC=C(C=C1)CC#CC1C(I)=CN=C(C=1Cl)N,Nc1ncc(I)c(C#CCc2ccc(O)cc2)c1Cl,smHD8_HighDiv,-5.52,-5.57,-5.50,-5.530000,0.036056,0.006520,19,-0.290526,-0.293158,-0.289474,-0.290526,0.0,0.0
4,HD8_HD005,OC1=CC=C(C=C1[C@H](CC1=CSN=C1)O)C(=C)C=C,C=CC(=C)c1ccc(O)c([C@@H](O)Cc2cnsc2)c1,smHD8_HighDiv,-6.15,-6.08,-5.96,-6.063333,0.096090,0.015848,19,-0.323684,-0.320000,-0.313684,-0.323684,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,HD8_DL287,OC(=O)C1=NN=C(O1)CC#CC(O)(F)F,O=C(O)c1nnc(CC#CC(O)(F)F)o1,smHD8_Druglike,-4.54,-4.37,-4.23,-4.380000,0.155242,0.035443,15,-0.302667,-0.291333,-0.282000,-0.302667,0.0,0.0
617,HD8_DL288,C(=C\CN)/C1=CC=C2C(=C1)C(=O)C=CN2,NC/C=C/c1ccc2[nH]ccc(=O)c2c1,smHD8_Druglike,-4.90,-4.99,-4.91,-4.933333,0.049329,0.009999,15,-0.326667,-0.332667,-0.327333,-0.326667,0.0,0.0
618,HD8_DL289,OC(=O)C/C=C/C1C=CC=C(C=1Cl)O,O=C(O)C/C=C/c1cccc(O)c1Cl,smHD8_Druglike,-4.05,-4.02,-4.05,-4.040000,0.017321,0.004287,14,-0.289286,-0.287143,-0.289286,-0.289286,0.0,0.0
619,HD8_DL290,OC(=O)/C=C/CCC1=NC2=C(N1)N=CC=C2,O=C(O)/C=C/CCc1nc2cccnc2[nH]1,smHD8_Druglike,-4.95,-4.98,-4.95,-4.960000,0.017321,0.003492,16,-0.309375,-0.311250,-0.309375,-0.309375,0.0,0.0
620,HD8_DL291,OC(=O)C1=NN=C(O1)C/C(=C/CC(=O)N)/C,C/C(=C\CC(N)=O)Cc1nnc(C(=O)O)o1,smHD8_Druglike,-4.67,-4.70,-4.78,-4.716667,0.056862,0.012056,16,-0.291875,-0.293750,-0.298750,-0.291875,0.0,0.0

In [ ]:
# Reference scores
NF2889=pd.read_csv("/content/drive/MyDrive/Cribado_Virtual_smHDAC8/Ledock_replicas/Sitio_alosterico_Ledock/DOCK_sitioAlosterico_NF2889.csv")
NF2889 = NF2889.rename(columns={'ID': 'ID_deNovo'})
NF2889

,ID_deNovo,Scores_Rep1,Scores_Rep2,Scores_Rep3,SMILES,SMILES_curated,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv,ID_VS_new,Database
0,NF2889_desH_PREP,-6.2,-6.02,-5.9,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,32,-0.19375,-0.188125,-0.184375,-0.19375,0.0,0.0,NF2889,Lig_NF2889

In [ ]:
# Average of the 3 replicates
NF2889['Docking_mean'] = NF2889[['Scores_Rep1', 'Scores_Rep2', 'Scores_Rep3']].mean(axis=1)

# Calculate pKd from the average
NF2889['pKd'] = (-NF2889['Docking_mean'] / 1.36).round(2)
NF2889

,ID_deNovo,Scores_Rep1,Scores_Rep2,Scores_Rep3,SMILES,SMILES_curated,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv,ID_VS_new,Database,Docking_mean,pKd
0,NF2889_desH_PREP,-6.2,-6.02,-5.9,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,32,-0.19375,-0.188125,-0.184375,-0.19375,0.0,0.0,NF2889,Lig_NF2889,-6.04,4.44

In [ ]:
# Merging
DB_DOCK = pd.concat([DB_DOCK_final, NF2889], join='inner', ignore_index=True)
DB_DOCK

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv
0,HD8_HD001,OC(=S)NC1=CC=C(C(=C1)/C=C/CC1=NC(=CN1)[C@H](C)...,C=Cc1ccc(NC(O)=S)cc1/C=C/Cc1nc([C@H](C)S)c[nH]1,smHD8_HighDiv,-6.44,-6.11,-5.82,23,-0.280000,-0.265652,-0.253043,-0.280000,0.0,0.0
1,HD8_HD002,OC1=CC=C(C(=C1)C1=CC(Cl)=CC(=C1O)Cl)CC(=O)C,CC(=O)Cc1ccc(O)cc1-c1cc(Cl)cc(Cl)c1O,smHD8_HighDiv,-5.47,-5.43,-5.46,20,-0.273500,-0.271500,-0.273000,-0.273500,0.0,0.0
2,HD8_HD003,OC(=O)C/C=C/C1=CNC(=NC1)C1=C(Br)C=NN1,O=C(O)C/C=C/C1=CNC(c2[nH]ncc2Br)=NC1,smHD8_HighDiv,-5.81,-5.84,-5.93,18,-0.322778,-0.324444,-0.329444,-0.322778,0.0,0.0
3,HD8_HD004,OC1=CC=C(C=C1)CC#CC1C(I)=CN=C(C=1Cl)N,Nc1ncc(I)c(C#CCc2ccc(O)cc2)c1Cl,smHD8_HighDiv,-5.52,-5.57,-5.50,19,-0.290526,-0.293158,-0.289474,-0.290526,0.0,0.0
4,HD8_HD005,OC1=CC=C(C=C1[C@H](CC1=CSN=C1)O)C(=C)C=C,C=CC(=C)c1ccc(O)c([C@@H](O)Cc2cnsc2)c1,smHD8_HighDiv,-6.15,-6.08,-5.96,19,-0.323684,-0.320000,-0.313684,-0.323684,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,HD8_DL288,C(=C\CN)/C1=CC=C2C(=C1)C(=O)C=CN2,NC/C=C/c1ccc2[nH]ccc(=O)c2c1,smHD8_Druglike,-4.90,-4.99,-4.91,15,-0.326667,-0.332667,-0.327333,-0.326667,0.0,0.0
618,HD8_DL289,OC(=O)C/C=C/C1C=CC=C(C=1Cl)O,O=C(O)C/C=C/c1cccc(O)c1Cl,smHD8_Druglike,-4.05,-4.02,-4.05,14,-0.289286,-0.287143,-0.289286,-0.289286,0.0,0.0
619,HD8_DL290,OC(=O)/C=C/CCC1=NC2=C(N1)N=CC=C2,O=C(O)/C=C/CCc1nc2cccnc2[nH]1,smHD8_Druglike,-4.95,-4.98,-4.95,16,-0.309375,-0.311250,-0.309375,-0.309375,0.0,0.0
620,HD8_DL291,OC(=O)C1=NN=C(O1)C/C(=C/CC(=O)N)/C,C/C(=C\CC(N)=O)Cc1nnc(C(=O)O)o1,smHD8_Druglike,-4.67,-4.70,-4.78,16,-0.291875,-0.293750,-0.298750,-0.291875,0.0,0.0
621,NF2889_desH_PREP,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,Lig_NF2889,-6.20,-6.02,-5.90,32,-0.193750,-0.188125,-0.184375,-0.193750,0.0,0.0

In [ ]:
df_Rep1 = DB_DOCK[['ID_deNovo', 'Scores_Rep1']].copy()
df_Rep2 = DB_DOCK[['ID_deNovo', 'Scores_Rep2']].copy()
df_Rep3 = DB_DOCK[['ID_deNovo', 'Scores_Rep3']].copy()
df_Rep1

            ID_deNovo  Scores_Rep1
0           HD8_HD001        -6.44
1           HD8_HD002        -5.47
2           HD8_HD003        -5.81
3           HD8_HD004        -5.52
4           HD8_HD005        -6.15
..                ...          ...
617         HD8_DL288        -4.90
618         HD8_DL289        -4.05
619         HD8_DL290        -4.95
620         HD8_DL291        -4.67
621  NF2889_desH_PREP        -6.20

[622 rows x 2 columns]

In [ ]:
# We extract the relevant columns into an array
Scores_Rep1 = df_Rep1['Scores_Rep1'].values
Scores_Rep2 = df_Rep2['Scores_Rep2'].values
Scores_Rep3 = df_Rep3['Scores_Rep3'].values
Scores_Rep1

array([-6.44, -5.47, -5.81, -5.52, -6.15, -5.99, -4.42, -6.09, -5.29,
       -5.63, -6.31, -5.48, -6.39, -5.31, -6.12, -5.04, -6.34, -5.63,
       -5.53, -6.07, -4.32, -5.19, -6.4 , -3.99, -5.11, -5.52, -4.97,
       -5.57, -4.97, -5.34, -5.08, -5.98, -4.72, -5.46, -5.09, -6.  ,
       -4.19, -5.2 , -4.94, -5.13, -6.11, -5.65, -6.87, -5.56, -4.86,
       -6.07, -6.12, -7.69, -5.98, -6.39, -5.43, -6.18, -5.39, -5.24,
       -5.05, -5.75, -5.  , -5.15, -5.32, -6.06, -5.55, -7.1 , -5.2 ,
       -6.16, -4.31, -6.39, -5.32, -5.03, -5.34, -4.85, -5.3 , -4.5 ,
       -5.86, -6.41, -4.55, -6.78, -5.21, -5.36, -4.67, -4.45, -4.25,
       -5.63, -5.08, -4.99, -4.99, -5.68, -5.51, -6.07, -5.4 , -5.4 ,
       -5.69, -5.26, -5.3 , -6.29, -5.44, -5.73, -6.12, -4.95, -4.85,
       -4.07, -5.68, -6.08, -5.47, -4.04, -4.6 , -5.33, -7.  , -6.61,
       -4.41, -5.59, -5.7 , -4.71, -4.67, -3.8 , -5.67, -4.59, -6.03,
       -5.  , -4.52, -6.18, -5.47, -3.85, -5.77, -5.66, -5.36, -5.09,
       -4.38, -4.87, -4.87, -4.77, -6.19, -4.35, -5.14, -4.67, -4.61,
       -5.63, -4.36, -4.76, -5.83, -4.92, -4.59, -4.92, -4.83, -6.18,
       -5.42, -4.54, -5.07, -6.58, -4.83, -6.58, -4.23, -3.98, -5.84,
       -4.97, -5.41, -5.33, -4.12, -6.15, -4.81, -6.06, -5.07, -5.69,
       -5.81, -4.96, -5.54, -4.82, -5.66, -4.76, -4.81, -3.98, -5.44,
       -6.23, -4.49, -5.38, -4.27, -4.65, -4.71, -5.75, -5.66, -4.13,
       -4.65, -6.54, -5.02, -4.39, -4.87, -5.65, -5.27, -4.53, -6.19,
       -5.68, -5.76, -5.65, -4.53, -5.06, -4.35, -4.22, -4.08, -6.72,
       -4.71, -3.88, -4.31, -5.22, -5.  , -5.74, -4.39, -5.05, -5.23,
       -4.87, -4.62, -5.96, -4.9 , -5.23, -5.24, -5.1 , -4.85, -5.02,
       -5.18, -5.54, -3.97, -4.38, -5.59, -3.99, -3.76, -5.01, -4.91,
       -4.89, -4.17, -5.24, -4.7 , -5.27, -6.12, -5.33, -4.68, -6.05,
       -5.53, -4.14, -5.65, -6.48, -5.21, -3.96, -6.12, -4.86, -5.55,
       -5.48, -4.49, -5.33, -4.67, -5.41, -4.57, -4.81, -4.73, -5.35,
       -5.82, -4.72, -3.94, -4.72, -5.47, -4.38, -5.04, -4.99, -4.37,
       -6.09, -5.44, -4.23, -5.62, -4.53, -4.67, -4.92, -3.58, -4.72,
       -6.94, -4.86, -5.4 , -3.84, -4.58, -4.1 , -4.59, -3.9 , -4.03,
       -6.55, -5.88, -5.14, -4.15, -5.05, -5.42, -4.96, -5.57, -5.97,
       -6.34, -5.8 , -6.33, -5.65, -5.38, -5.03, -5.02, -4.43, -5.53,
       -4.99, -5.32, -3.91, -5.9 , -4.02, -4.77, -4.9 , -4.49, -4.24,
       -4.75, -4.51, -4.19, -4.88, -2.75, -4.22, -4.73, -3.97, -3.74,
       -3.6 , -4.48, -4.06, -3.96, -4.66, -5.83, -5.03, -5.26, -4.57,
       -4.6 , -4.28, -4.28, -5.13, -4.79, -5.9 , -6.5 , -6.46, -6.13,
       -6.97, -5.03, -6.65, -5.79, -5.54, -6.7 , -5.16, -5.58, -5.97,
       -5.98, -5.56, -4.91, -5.9 , -6.67, -5.43, -5.32, -6.  , -5.32,
       -4.75, -6.01, -5.45, -6.02, -5.56, -3.98, -5.96, -4.85, -6.26,
       -4.17, -5.1 , -4.32, -5.59, -6.29, -5.8 , -4.11, -7.06, -5.8 ,
       -4.92, -4.86, -5.49, -5.02, -5.37, -4.94, -6.41, -6.06, -4.62,
       -5.89, -4.86, -4.18, -4.74, -6.63, -5.94, -6.56, -4.42, -5.13,
       -6.3 , -5.11, -6.18, -5.  , -4.39, -6.05, -5.06, -4.2 , -4.91,
       -4.99, -6.75, -4.76, -6.09, -5.96, -6.03, -6.52, -6.51, -4.09,
       -5.24, -4.57, -4.08, -6.32, -4.5 , -4.86, -4.48, -4.92, -6.15,
       -4.95, -4.06, -5.28, -3.88, -3.69, -4.46, -5.07, -5.53, -5.08,
       -5.1 , -5.68, -5.92, -4.45, -3.92, -5.42, -5.79, -5.84, -5.65,
       -4.62, -4.66, -5.68, -5.72, -6.88, -4.43, -4.65, -5.22, -5.63,
       -4.88, -5.61, -5.24, -4.17, -4.  , -4.06, -4.02, -4.03, -5.62,
       -4.8 , -4.89, -6.03, -5.83, -4.83, -5.19, -5.48, -5.35, -5.57,
       -5.25, -4.72, -5.72, -4.65, -5.59, -5.6 , -5.62, -5.31, -5.35,
       -4.63, -3.98, -4.18, -4.79, -5.24, -5.36, -5.85, -4.74, -4.12,
       -4.89, -4.25, -4.39, -6.37, -4.65, -4.58, -5.75, -4.59, -4.63,
       -4.94, -6.28, -5.11, -4.27, -4.56, -5.04, -4.75, -5.3 , -4.26,
       -5.17, -5.11, -4.31, -4.72, -5.01, -5.32, -5.43, -4.02, -6.11,
       -4.95, -4.76, -5.44, -5.58, -5.5 , -4.68, -5.24, -5.8 , -4.61,
       -5.  , -6.21, -4.86, -5.93, -4.63, -6.49, -4.33, -4.95, -5.21,
       -4.59, -5.11, -6.2 , -5.82, -5.  , -5.98, -4.31, -5.75, -4.97,
       -5.07, -4.24, -4.73, -4.62, -4.67, -5.9 , -4.72, -6.1 , -4.36,
       -4.56, -4.6 , -6.62, -6.22, -5.25, -5.03, -5.13, -5.12, -4.25,
       -5.12, -5.53, -5.11, -4.78, -3.94, -5.45, -5.09, -5.08, -6.43,
       -6.03, -4.61, -4.21, -5.23, -5.07, -5.41, -4.76, -4.2 , -4.57,
       -4.22, -4.83, -5.13, -4.87, -5.36, -6.01, -5.47, -4.84, -5.14,
       -5.09, -6.08, -4.72, -4.54, -6.19, -5.18, -5.29, -5.12, -4.36,
       -5.27, -4.56, -5.24, -4.84, -5.77, -3.75, -5.51, -4.2 , -6.63,
       -4.85, -4.73, -5.23, -4.62, -5.12, -5.1 , -3.9 , -4.26, -5.95,
       -5.52, -6.33, -4.52, -5.06, -3.87, -4.72, -5.54, -5.38, -5.53,
       -4.68, -4.  , -4.75, -4.43, -4.54, -4.9 , -4.05, -4.95, -4.67,
       -6.2 ])

In [ ]:
# Mean and standard deviation for Rep1
mu_rep1 = np.mean(Scores_Rep1)
sigma_rep1 = np.std(Scores_Rep1)

# Mean and standard deviation for Rep2
mu_rep2 = np.mean(Scores_Rep2)
sigma_rep2 = np.std(Scores_Rep2)

# Mean and standard deviation for Rep3
mu_rep3 = np.mean(Scores_Rep3)
sigma_rep3 = np.std(Scores_Rep3)

##Z-Score

$Z_j^i = \frac{1}{n} \sum_j\frac{s_j^i - \mu_j}{\sigma_j}$

In [ ]:
df = DB_DOCK[['ID_deNovo']].copy()

#  Z-scores for each method
df['Z_Rep1'] = (df_Rep1['Scores_Rep1'] - mu_rep1) / sigma_rep1
df['Z_Rep2'] = (df_Rep2['Scores_Rep2'] - mu_rep2) / sigma_rep2
df['Z_Rep3'] = (df_Rep3['Scores_Rep3'] - mu_rep3) / sigma_rep3

# Combined Z-score (average of the Z-scores)
df['Z_Score_Combined'] = (df['Z_Rep1'] + df['Z_Rep2'] + df['Z_Rep3']) / 3


# rank the combined Z-score
df["R_Z_Score"] = df["Z_Score_Combined"].rank(ascending=True, method="dense")

print("Estadísticas calculadas:")
print(f"REP1: μ={mu_rep1:.4f}, σ={sigma_rep1:.4f}")
print(f"REP2: μ={mu_rep2:.4f}, σ={sigma_rep2:.4f}")
print(f"REP3: μ={mu_rep3:.4f}, σ={sigma_rep3:.4f}")
print("\nResultados:")
print(df[["ID_deNovo", "Z_Score_Combined", "R_Z_Score"]].head())

Estadísticas calculadas:
REP1: μ=-5.1688, σ=0.7334
REP2: μ=-5.1641, σ=0.7361
REP3: μ=-5.1703, σ=0.7180

Resultados:
   ID_deNovo  Z_Score_Combined  R_Z_Score
0  HD8_HD001         -1.307737       64.0
1  HD8_HD002         -0.391815      213.0
2  HD8_HD003         -0.950196      116.0
3  HD8_HD004         -0.496506      189.0
4  HD8_HD005         -1.227335       70.0

In [ ]:
df_S = DB_DOCK.merge(df, on='ID_deNovo', how='left')
df_S

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv,Z_Rep1,Z_Rep2,Z_Rep3,Z_Score_Combined,R_Z_Score
0,HD8_HD001,OC(=S)NC1=CC=C(C(=C1)/C=C/CC1=NC(=CN1)[C@H](C)...,C=Cc1ccc(NC(O)=S)cc1/C=C/Cc1nc([C@H](C)S)c[nH]1,smHD8_HighDiv,-6.44,-6.11,-5.82,23,-0.280000,-0.265652,-0.253043,-0.280000,0.0,0.0,-1.733326,-1.285005,-0.904880,-1.307737,64.0
1,HD8_HD002,OC1=CC=C(C(=C1)C1=CC(Cl)=CC(=C1O)Cl)CC(=O)C,CC(=O)Cc1ccc(O)cc1-c1cc(Cl)cc(Cl)c1O,smHD8_HighDiv,-5.47,-5.43,-5.46,20,-0.273500,-0.271500,-0.273000,-0.273500,0.0,0.0,-0.410703,-0.361225,-0.403517,-0.391815,213.0
2,HD8_HD003,OC(=O)C/C=C/C1=CNC(=NC1)C1=C(Br)C=NN1,O=C(O)C/C=C/C1=CNC(c2[nH]ncc2Br)=NC1,smHD8_HighDiv,-5.81,-5.84,-5.93,18,-0.322778,-0.324444,-0.329444,-0.322778,0.0,0.0,-0.874303,-0.918210,-1.058074,-0.950196,116.0
3,HD8_HD004,OC1=CC=C(C=C1)CC#CC1C(I)=CN=C(C=1Cl)N,Nc1ncc(I)c(C#CCc2ccc(O)cc2)c1Cl,smHD8_HighDiv,-5.52,-5.57,-5.50,19,-0.290526,-0.293158,-0.289474,-0.290526,0.0,0.0,-0.478879,-0.551415,-0.459224,-0.496506,189.0
4,HD8_HD005,OC1=CC=C(C=C1[C@H](CC1=CSN=C1)O)C(=C)C=C,C=CC(=C)c1ccc(O)c([C@@H](O)Cc2cnsc2)c1,smHD8_HighDiv,-6.15,-6.08,-5.96,19,-0.323684,-0.320000,-0.313684,-0.323684,0.0,0.0,-1.337902,-1.244250,-1.099854,-1.227335,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,HD8_DL288,C(=C\CN)/C1=CC=C2C(=C1)C(=O)C=CN2,NC/C=C/c1ccc2[nH]ccc(=O)c2c1,smHD8_Druglike,-4.90,-4.99,-4.91,15,-0.326667,-0.332667,-0.327333,-0.326667,0.0,0.0,0.366509,0.236514,0.362453,0.321825,374.0
618,HD8_DL289,OC(=O)C/C=C/C1C=CC=C(C=1Cl)O,O=C(O)C/C=C/c1cccc(O)c1Cl,smHD8_Druglike,-4.05,-4.02,-4.05,14,-0.289286,-0.287143,-0.289286,-0.289286,0.0,0.0,1.525508,1.554259,1.560153,1.546640,589.0
619,HD8_DL290,OC(=O)/C=C/CCC1=NC2=C(N1)N=CC=C2,O=C(O)/C=C/CCc1nc2cccnc2[nH]1,smHD8_Druglike,-4.95,-4.98,-4.95,16,-0.309375,-0.311250,-0.309375,-0.309375,0.0,0.0,0.298332,0.250099,0.306746,0.285059,365.0
620,HD8_DL291,OC(=O)C1=NN=C(O1)C/C(=C/CC(=O)N)/C,C/C(=C\CC(N)=O)Cc1nnc(C(=O)O)o1,smHD8_Druglike,-4.67,-4.70,-4.78,16,-0.291875,-0.293750,-0.298750,-0.291875,0.0,0.0,0.680120,0.630479,0.543501,0.618033,451.0
621,NF2889_desH_PREP,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,Lig_NF2889,-6.20,-6.02,-5.90,32,-0.193750,-0.188125,-0.184375,-0.193750,0.0,0.0,-1.406079,-1.162740,-1.016294,-1.195037,79.0

In [ ]:
df_S.sort_values(by='R_Z_Score', ascending=True, inplace=True)
df_S

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,NumHeavyAtoms,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv,Z_Rep1,Z_Rep2,Z_Rep3,Z_Score_Combined,R_Z_Score
47,HD8_HD048,OC1C(SCC2=NNC(=S)N2)=CC(=CC=1)C1=C(Cl)C=NN1,Oc1ccc(-c2[nH]ncc2Cl)cc1SCc1n[nH]c(=S)[nH]1,smHD8_HighDiv,-7.69,-7.22,-7.82,21,-0.366190,-0.343810,-0.372381,-0.366190,0.0,0.0,-3.437736,-2.792939,-3.690227,-3.306968,1.0
367,HD8_DL038,OC1=CC=C(C=C1)C(=O)O[C@H](C1=NN=CN1)C1=NNC=C1,O=C(O[C@@H](c1cc[nH]n1)c1nnc[nH]1)c1ccc(O)cc1,smHD8_Druglike,-7.06,-7.33,-7.29,21,-0.336190,-0.349048,-0.347143,-0.336190,0.0,0.0,-2.578713,-2.942374,-2.952110,-2.824399,2.0
42,HD8_HD043,OC1=CC=C(C=C1)C(=C)/C=C/C1=C(N=CN1)C1=NNN=C1,C=C(/C=C/c1[nH]cnc1-c1cn[nH]n1)c1ccc(O)cc1,smHD8_HighDiv,-6.87,-7.12,-7.08,21,-0.327143,-0.339048,-0.337143,-0.327143,0.0,0.0,-2.319643,-2.657090,-2.659649,-2.545460,3.0
270,HD8_HD271,N/C(=C\C1=C(Cl)C=NN1)/C(/C=C/N(=O)=O)(N)N,N/C(=C\c1[nH]ncc1Cl)C(N)(N)/C=C/[N+](=O)[O-],smHD8_HighDiv,-6.94,-6.76,-6.68,17,-0.408235,-0.397647,-0.392941,-0.408235,0.0,0.0,-2.415090,-2.168030,-2.102579,-2.228566,4.0
401,HD8_DL072,OC(=O)C1=NN=C(N1)CCC1=NC=CC(=N1)NCCC[NH3+],NCCCNc1ccnc(CCc2nnc(C(=O)O)[nH]2)n1,smHD8_Druglike,-6.03,-7.10,-7.16,21,-0.287143,-0.338095,-0.340952,-0.287143,0.0,0.0,-1.174279,-2.629920,-2.771063,-2.191754,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,HD8_HD223,OC(=O)CC1C(C(=C)/C=C/CC)=CC=C(C=1)O,C=C(/C=C/CC)c1ccc(O)cc1CC(=O)O,smHD8_HighDiv,-3.76,-3.68,-3.74,17,-0.221176,-0.216471,-0.220000,-0.221176,0.0,0.0,1.920931,2.016149,1.991882,1.976321,618.0
418,HD8_DL089,OC1C=CC(=CC=1[C@H](CN)C)Cl,C[C@@H](CN)c1cc(Cl)ccc1O,smHD8_Druglike,-3.69,-3.70,-3.67,12,-0.307500,-0.308333,-0.305833,-0.307500,0.0,0.0,2.016378,1.988979,2.089369,2.031575,619.0
268,HD8_HD269,S[C@H](C(=O)C1=CC=CC=C1)C(=O)O,O=C(O)[C@H](S)C(=O)c1ccccc1,smHD8_HighDiv,-3.58,-3.64,-3.45,13,-0.275385,-0.280000,-0.265385,-0.275385,0.0,0.0,2.166367,2.070489,2.395757,2.210871,620.0
315,HD8_HD316,O[S@@](=O)C1=CC=CC(=C1)NC=C,C=CNc1cccc([S@](=O)O)c1,smHD8_HighDiv,-3.60,-3.57,-3.46,12,-0.300000,-0.297500,-0.288333,-0.300000,0.0,0.0,2.139096,2.165584,2.381830,2.228837,621.0
310,HD8_HD311,N[C@@](CI)(C)C(=O)[O-],C[C@@](N)(CI)C(=O)O,smHD8_HighDiv,-2.75,-2.47,-2.74,8,-0.343750,-0.308750,-0.342500,-0.343750,0.0,0.0,3.298095,3.659933,3.384556,3.447528,622.0

In [ ]:
# Save
df_S.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/ConsensoRep_Zscore_S_smHD8.csv", index=False)

In [ ]:
top_5_Z_describe = df_S.nsmallest(5, 'Z_Score_Combined')
#print(top_10_Z[['ID_VS', 'ID_VS_new','SMILES_curated', 'Database', 'Z_Score_Combined', 'R_Z_Score_Allos']])
top_5_Z = top_5_Z_describe[['ID_deNovo','SMILES_curated','Database','Z_Score_Combined','R_Z_Score']]

In [ ]:
#S ave
top_5_Z.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/Rank5ConsensoRep_Zscore_S.csv", index=False)
top_5_Z_describe.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/Rank5ConsensoRep_Zscore_S_describe.csv", index=False)

##Zscore_LE

In [ ]:
df_Rep1_LE = DB_DOCK[['ID_deNovo', 'LE_Rep1']].copy()
df_Rep2_LE = DB_DOCK[['ID_deNovo', 'LE_Rep2']].copy()
df_Rep3_LE = DB_DOCK[['ID_deNovo','LE_Rep3']].copy()
df_Rep1_LE

            ID_deNovo   LE_Rep1
0           HD8_HD001 -0.280000
1           HD8_HD002 -0.273500
2           HD8_HD003 -0.322778
3           HD8_HD004 -0.290526
4           HD8_HD005 -0.323684
..                ...       ...
617         HD8_DL288 -0.326667
618         HD8_DL289 -0.289286
619         HD8_DL290 -0.309375
620         HD8_DL291 -0.291875
621  NF2889_desH_PREP -0.193750

[622 rows x 2 columns]

In [ ]:
# We extract the relevant columns into an array
Rep1_LE = df_Rep1_LE['LE_Rep1'].values
Rep2_LE = df_Rep2_LE['LE_Rep2'].values
Rep3_LE = df_Rep3_LE['LE_Rep3'].values

In [ ]:
# Mean and standard deviation for Rep1
mu_rep1_LE = np.mean(Rep1_LE)
sigma_rep1_LE = np.std(Rep1_LE)

# Mean and standard deviation for Rep2
mu_rep2_LE = np.mean(Rep2_LE)
sigma_rep2_LE = np.std(Rep2_LE)

# Mean and standard deviation for Rep3
mu_rep3_LE = np.mean(Rep3_LE)
sigma_rep3_LE = np.std(Rep3_LE)

In [ ]:
#Z-score_LE

df_LE = DB_DOCK[['ID_deNovo']].copy()

# Z-scores for each method
df_LE['Z_Rep1_LE'] = (df_Rep1_LE['LE_Rep1'] - mu_rep1_LE) / sigma_rep1_LE
df_LE['Z_Rep2_LE'] = (df_Rep2_LE['LE_Rep2'] - mu_rep2_LE) / sigma_rep2_LE
df_LE['Z_Rep3_LE'] = (df_Rep3_LE['LE_Rep3'] - mu_rep3_LE) / sigma_rep3_LE

# Combined Z-score (average of the Z-scores)
df_LE['Z_Score_Combined_LE'] = (df_LE['Z_Rep1_LE'] + df_LE['Z_Rep2_LE'] + df_LE['Z_Rep3_LE']) / 3


# Rank the combined Z-score
df_LE["R_Z_Score_LE"] = df_LE["Z_Score_Combined_LE"].rank(ascending=True, method="dense")

print("Estadísticas calculadas:")
print(f"LE_Rep1: μ={mu_rep1_LE:.4f}, σ={sigma_rep1_LE:.4f}")
print(f"LE_Rep1: μ={mu_rep2_LE:.4f}, σ={sigma_rep2_LE:.4f}")
print(f"LE_Rep1: μ={mu_rep3_LE:.4f}, σ={sigma_rep3_LE:.4f}")
print("\nResultados:")
print(df_LE[["ID_deNovo", "Z_Score_Combined_LE", "R_Z_Score_LE"]].head())

Estadísticas calculadas:
LE_Rep1: μ=-0.3093, σ=0.0470
LE_Rep1: μ=-0.3089, σ=0.0464
LE_Rep1: μ=-0.3094, σ=0.0465

Resultados:
   ID_deNovo  Z_Score_Combined_LE  R_Z_Score_LE
0  HD8_HD001             0.922881         520.0
1  HD8_HD002             0.784024         497.0
2  HD8_HD003            -0.350520         207.0
3  HD8_HD004             0.389533         399.0
4  HD8_HD005            -0.212114         244.0

In [ ]:
df_final = df_S.merge(df_LE, on='ID_deNovo', how='left')
df_final

,ID_deNovo,SMILES,SMILES_curated,Database,Scores_Rep1,Scores_Rep2,Scores_Rep3,NumHeavyAtoms,LE_Rep1,LE_Rep2,...,Z_Rep1,Z_Rep2,Z_Rep3,Z_Score_Combined,R_Z_Score,Z_Rep1_LE,Z_Rep2_LE,Z_Rep3_LE,Z_Score_Combined_LE,R_Z_Score_LE
0,HD8_HD048,OC1C(SCC2=NNC(=S)N2)=CC(=CC=1)C1=C(Cl)C=NN1,Oc1ccc(-c2[nH]ncc2Cl)cc1SCc1n[nH]c(=S)[nH]1,smHD8_HighDiv,-7.69,-7.22,-7.82,21,-0.366190,-0.343810,...,-3.437736,-2.792939,-3.690227,-3.306968,1.0,-1.210901,-0.752614,-1.352503,-1.105339,88.0
1,HD8_DL038,OC1=CC=C(C=C1)C(=O)O[C@H](C1=NN=CN1)C1=NNC=C1,O=C(O[C@@H](c1cc[nH]n1)c1nnc[nH]1)c1ccc(O)cc1,smHD8_Druglike,-7.06,-7.33,-7.29,21,-0.336190,-0.349048,...,-2.578713,-2.942374,-2.952110,-2.824399,2.0,-0.572230,-0.865556,-0.810141,-0.749309,134.0
2,HD8_HD043,OC1=CC=C(C=C1)C(=C)/C=C/C1=C(N=CN1)C1=NNN=C1,C=C(/C=C/c1[nH]cnc1-c1cn[nH]n1)c1ccc(O)cc1,smHD8_HighDiv,-6.87,-7.12,-7.08,21,-0.327143,-0.339048,...,-2.319643,-2.657090,-2.659649,-2.545460,3.0,-0.379615,-0.649939,-0.595243,-0.541599,173.0
3,HD8_HD271,N/C(=C\C1=C(Cl)C=NN1)/C(/C=C/N(=O)=O)(N)N,N/C(=C\c1[nH]ncc1Cl)C(N)(N)/C=C/[N+](=O)[O-],smHD8_HighDiv,-6.94,-6.76,-6.68,17,-0.408235,-0.397647,...,-2.415090,-2.168030,-2.102579,-2.228566,4.0,-2.105994,-1.913446,-1.794338,-1.937926,19.0
4,HD8_DL072,OC(=O)C1=NN=C(N1)CCC1=NC=CC(=N1)NCCC[NH3+],NCCCNc1ccnc(CCc2nnc(C(=O)O)[nH]2)n1,smHD8_Druglike,-6.03,-7.10,-7.16,21,-0.287143,-0.338095,...,-1.174279,-2.629920,-2.771063,-2.191754,5.0,0.471946,-0.629404,-0.677108,-0.278189,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,HD8_HD223,OC(=O)CC1C(C(=C)/C=C/CC)=CC=C(C=1)O,C=C(/C=C/CC)c1ccc(O)cc1CC(=O)O,smHD8_HighDiv,-3.76,-3.68,-3.74,17,-0.221176,-0.216471,...,1.920931,2.016149,1.991882,1.976321,618.0,1.876307,1.993038,1.922135,1.930493,612.0
618,HD8_DL089,OC1C=CC(=CC=1[C@H](CN)C)Cl,C[C@@H](CN)c1cc(Cl)ccc1O,smHD8_Druglike,-3.69,-3.70,-3.67,12,-0.307500,-0.308333,...,2.016378,1.988979,2.089369,2.031575,619.0,0.038562,0.012315,0.077593,0.042824,311.0
619,HD8_HD269,S[C@H](C(=O)C1=CC=CC=C1)C(=O)O,O=C(O)[C@H](S)C(=O)c1ccccc1,smHD8_HighDiv,-3.58,-3.64,-3.45,13,-0.275385,-0.280000,...,2.166367,2.070489,2.395757,2.210871,620.0,0.722268,0.623232,0.946828,0.764109,492.0
620,HD8_HD316,O[S@@](=O)C1=CC=CC(=C1)NC=C,C=CNc1cccc([S@](=O)O)c1,smHD8_HighDiv,-3.60,-3.57,-3.46,12,-0.300000,-0.297500,...,2.139096,2.165584,2.381830,2.228837,621.0,0.198230,0.245901,0.453665,0.299265,377.0
621,HD8_HD311,N[C@@](CI)(C)C(=O)[O-],C[C@@](N)(CI)C(=O)O,smHD8_HighDiv,-2.75,-2.47,-2.74,8,-0.343750,-0.308750,...,3.298095,3.659933,3.384556,3.447528,622.0,-0.733165,0.003331,-0.710367,-0.480067,184.0

In [ ]:
# Save
df_final.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/S_LE_ConsensoReps_Zscore_smHD8.csv", index=False)

In [ ]:
# Save
DB_1 = pd.read_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/MolecularDescriptors_df_highdiv.csv")
DB_2 = pd.read_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/MolecularDescriptors_df_druglike.csv")

DB_denovo = pd.concat([DB_1, DB_2], ignore_index=True)
DB_denovo = pd.concat([DB_denovo, NF2889], ignore_index=True)
DB_denovo

,ID_deNovo,SMILES,Name,InChI,Formula,MW,LogP,pKd,Structure,Synthesize,...,Scores_Rep2,Scores_Rep3,LE_Rep1,LE_Rep2,LE_Rep3,LE_mean,LE_std,LE_cv,ID_VS_new,Docking_mean
0,HD8_HD001,OC(=S)NC1=CC=C(C(=C1)/C=C/CC1=NC(=CN1)[C@H](C)...,6/000000103,InChI=1S/C17H19N3OS2/c1-3-12-7-8-14(19-17(21)2...,C17H19N3OS2,345.096954,3.45,4.63,-11.50,24.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HD8_HD002,OC1=CC=C(C(=C1)C1=CC(Cl)=CC(=C1O)Cl)CC(=O)C,3/000000076,InChI=1S/C15H12Cl2O3/c1-8(18)4-9-2-3-11(19)7-1...,C15H12O3Cl2,310.016350,4.09,4.54,-6.86,15.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HD8_HD003,OC(=O)C/C=C/C1=CNC(=NC1)C1=C(Br)C=NN1,4/000000002,InChI=1S/C11H11BrN4O2/c12-8-6-15-16-10(8)11-13...,C11H11N4O2Br,310.006538,1.27,4.50,-2.49,23.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HD8_HD004,OC1=CC=C(C=C1)CC#CC1C(I)=CN=C(C=1Cl)N,3/000000134,InChI=1S/C14H10ClIN2O/c15-13-11(12(16)8-18-14(...,C14H10N2OClI,383.952639,4.38,4.48,-5.80,16.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HD8_HD005,OC1=CC=C(C=C1[C@H](CC1=CSN=C1)O)C(=C)C=C,3/000000315,InChI=1S/C15H15NO2S/c1-3-10(2)12-4-5-14(17)13(...,C15H15NO2S,273.082350,2.62,4.34,-5.32,19.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,HD8_DL288,C(=C\CN)/C1=CC=C2C(=C1)C(=O)C=CN2,6/000000083,InChI=1S/C12H12N2O/c13-6-1-2-9-3-4-11-10(8-9)1...,C12H12N2O,200.094963,1.51,3.01,-9.66,3.58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,HD8_DL289,OC(=O)C/C=C/C1C=CC=C(C=1Cl)O,4/000000101,InChI=1S/C10H9ClO3/c11-10-7(3-1-5-8(10)12)4-2-...,C10H9O3Cl,212.024022,2.27,3.01,-2.70,2.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,HD8_DL290,OC(=O)/C=C/CCC1=NC2=C(N1)N=CC=C2,4/000000122,InChI=1S/C11H11N3O2/c15-10(16)6-2-1-5-9-13-8-4...,C11H11N3O2,217.085127,1.00,3.01,-10.12,4.81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,HD8_DL291,OC(=O)C1=NN=C(O1)C/C(=C/CC(=O)N)/C,6/000000014,InChI=1S/C9H11N3O4/c1-5(2-3-6(10)13)4-7-11-12-...,C9H11N3O4,225.074956,-0.13,3.00,-6.37,2.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,NF2889_desH_PREP,CN1CCC2(CC1)c1ccccc1N(Cc1ccc(C(=O)N[O])s1)[C@H...,NaN,NaN,NaN,NaN,NaN,4.44,NaN,NaN,...,-6.02,-5.9,-0.19375,-0.188125,-0.184375,-0.19375,0.0,0.0,NF2889,-6.04

In [ ]:
DB_denovo_final = df_final.merge(DB_denovo, on='ID_deNovo', how='left')
DB_denovo_final

,ID_deNovo,SMILES_x,SMILES_curated_x,Database_x,Scores_Rep1_x,Scores_Rep2_x,Scores_Rep3_x,NumHeavyAtoms_x,LE_Rep1_x,LE_Rep2_x,...,Scores_Rep2_y,Scores_Rep3_y,LE_Rep1_y,LE_Rep2_y,LE_Rep3_y,LE_mean_y,LE_std_y,LE_cv_y,ID_VS_new,Docking_mean
0,HD8_HD048,OC1C(SCC2=NNC(=S)N2)=CC(=CC=1)C1=C(Cl)C=NN1,Oc1ccc(-c2[nH]ncc2Cl)cc1SCc1n[nH]c(=S)[nH]1,smHD8_HighDiv,-7.69,-7.22,-7.82,21,-0.366190,-0.343810,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HD8_DL038,OC1=CC=C(C=C1)C(=O)O[C@H](C1=NN=CN1)C1=NNC=C1,O=C(O[C@@H](c1cc[nH]n1)c1nnc[nH]1)c1ccc(O)cc1,smHD8_Druglike,-7.06,-7.33,-7.29,21,-0.336190,-0.349048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HD8_HD043,OC1=CC=C(C=C1)C(=C)/C=C/C1=C(N=CN1)C1=NNN=C1,C=C(/C=C/c1[nH]cnc1-c1cn[nH]n1)c1ccc(O)cc1,smHD8_HighDiv,-6.87,-7.12,-7.08,21,-0.327143,-0.339048,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HD8_HD271,N/C(=C\C1=C(Cl)C=NN1)/C(/C=C/N(=O)=O)(N)N,N/C(=C\c1[nH]ncc1Cl)C(N)(N)/C=C/[N+](=O)[O-],smHD8_HighDiv,-6.94,-6.76,-6.68,17,-0.408235,-0.397647,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HD8_DL072,OC(=O)C1=NN=C(N1)CCC1=NC=CC(=N1)NCCC[NH3+],NCCCNc1ccnc(CCc2nnc(C(=O)O)[nH]2)n1,smHD8_Druglike,-6.03,-7.10,-7.16,21,-0.287143,-0.338095,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,HD8_HD223,OC(=O)CC1C(C(=C)/C=C/CC)=CC=C(C=1)O,C=C(/C=C/CC)c1ccc(O)cc1CC(=O)O,smHD8_HighDiv,-3.76,-3.68,-3.74,17,-0.221176,-0.216471,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,HD8_DL089,OC1C=CC(=CC=1[C@H](CN)C)Cl,C[C@@H](CN)c1cc(Cl)ccc1O,smHD8_Druglike,-3.69,-3.70,-3.67,12,-0.307500,-0.308333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,HD8_HD269,S[C@H](C(=O)C1=CC=CC=C1)C(=O)O,O=C(O)[C@H](S)C(=O)c1ccccc1,smHD8_HighDiv,-3.58,-3.64,-3.45,13,-0.275385,-0.280000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
620,HD8_HD316,O[S@@](=O)C1=CC=CC(=C1)NC=C,C=CNc1cccc([S@](=O)O)c1,smHD8_HighDiv,-3.60,-3.57,-3.46,12,-0.300000,-0.297500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
621,HD8_HD311,N[C@@](CI)(C)C(=O)[O-],C[C@@](N)(CI)C(=O)O,smHD8_HighDiv,-2.75,-2.47,-2.74,8,-0.343750,-0.308750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
DB_denovo_final.columns

Index(['ID_deNovo', 'SMILES_x', 'SMILES_curated_x', 'Database_x',
       'Scores_Rep1_x', 'Scores_Rep2_x', 'Scores_Rep3_x', 'NumHeavyAtoms_x',
       'LE_Rep1_x', 'LE_Rep2_x', 'LE_Rep3_x', 'LE_mean_x', 'LE_std_x',
       'LE_cv_x', 'Z_Rep1', 'Z_Rep2', 'Z_Rep3', 'Z_Score_Combined',
       'R_Z_Score', 'Z_Rep1_LE', 'Z_Rep2_LE', 'Z_Rep3_LE',
       'Z_Score_Combined_LE', 'R_Z_Score_LE', 'SMILES_y', 'Name', 'InChI',
       'Formula', 'MW', 'LogP', 'pKd', 'Structure', 'Synthesize', 'Chemical',
       'SMILES_curated_y', 'Database_y', 'HBA', 'HBD', 'LOGP', 'TPSA', 'RB',
       'SA_score', 'NumCarbons', 'NumOxygens', 'NumNitrogens',
       'FractionOfCarbons', 'FractionOfOxygens', 'FractionOfNitrogens', 'CSP3',
       'FractionOfChiralCarbons', 'NumHeavyAtoms_y', 'Ring', 'AliphaticRing',
       'AromaticRing', 'Heterocycle', 'AliphaticHeterocycle',
       'AromaticHeterocycle', 'SpiroAtom', 'BridgeheadAtom', 'Scores_Rep1_y',
       'Scores_Rep2_y', 'Scores_Rep3_y', 'LE_Rep1_y', 'LE_Rep2_y', 'LE_Rep3_y',
       'LE_mean_y', 'LE_std_y', 'LE_cv_y', 'ID_VS_new', 'Docking_mean'],
      dtype='object')

In [ ]:
columnas_deseadas = ['ID_deNovo', 'SMILES_x', 'SMILES_curated_x', 'Database_x', 'Formula', 'pKd',
       'Scores_Rep1_x', 'Scores_Rep2_x', 'Scores_Rep3_x', 'LE_Rep1_x', 'LE_Rep2_x', 'LE_Rep3_x',
        'Z_Rep1', 'Z_Rep2', 'Z_Rep3',
       'Z_Score_Combined', 'R_Z_Score', 'Z_Rep1_LE', 'Z_Rep2_LE', 'Z_Rep3_LE',
       'Z_Score_Combined_LE', 'R_Z_Score_LE'
      ]

DB_filtrado = DB_denovo_final[columnas_deseadas]
DB_filtrado = DB_denovo_final[columnas_deseadas].rename(columns=lambda x: x.replace('_x',''))
DB_filtrado

,ID_deNovo,SMILES,SMILES_curated,Database,Formula,pKd,Scores_Rep1,Scores_Rep2,Scores_Rep3,LE_Rep1,...,Z_Rep1,Z_Rep2,Z_Rep3,Z_Score_Combined,R_Z_Score,Z_Rep1_LE,Z_Rep2_LE,Z_Rep3_LE,Z_Score_Combined_LE,R_Z_Score_LE
0,HD8_HD048,OC1C(SCC2=NNC(=S)N2)=CC(=CC=1)C1=C(Cl)C=NN1,Oc1ccc(-c2[nH]ncc2Cl)cc1SCc1n[nH]c(=S)[nH]1,smHD8_HighDiv,C12H10N5OS2Cl,3.78,-7.69,-7.22,-7.82,-0.366190,...,-3.437736,-2.792939,-3.690227,-3.306968,1.0,-1.210901,-0.752614,-1.352503,-1.105339,88.0
1,HD8_DL038,OC1=CC=C(C=C1)C(=O)O[C@H](C1=NN=CN1)C1=NNC=C1,O=C(O[C@@H](c1cc[nH]n1)c1nnc[nH]1)c1ccc(O)cc1,smHD8_Druglike,C13H11N5O3,4.04,-7.06,-7.33,-7.29,-0.336190,...,-2.578713,-2.942374,-2.952110,-2.824399,2.0,-0.572230,-0.865556,-0.810141,-0.749309,134.0
2,HD8_HD043,OC1=CC=C(C=C1)C(=C)/C=C/C1=C(N=CN1)C1=NNN=C1,C=C(/C=C/c1[nH]cnc1-c1cn[nH]n1)c1ccc(O)cc1,smHD8_HighDiv,C15H13N5O,3.79,-6.87,-7.12,-7.08,-0.327143,...,-2.319643,-2.657090,-2.659649,-2.545460,3.0,-0.379615,-0.649939,-0.595243,-0.541599,173.0
3,HD8_HD271,N/C(=C\C1=C(Cl)C=NN1)/C(/C=C/N(=O)=O)(N)N,N/C(=C\c1[nH]ncc1Cl)C(N)(N)/C=C/[N+](=O)[O-],smHD8_HighDiv,C8H11N6O2Cl,3.13,-6.94,-6.76,-6.68,-0.408235,...,-2.415090,-2.168030,-2.102579,-2.228566,4.0,-2.105994,-1.913446,-1.794338,-1.937926,19.0
4,HD8_DL072,OC(=O)C1=NN=C(N1)CCC1=NC=CC(=N1)NCCC[NH3+],NCCCNc1ccnc(CCc2nnc(C(=O)O)[nH]2)n1,smHD8_Druglike,C12H18N7O2,3.80,-6.03,-7.10,-7.16,-0.287143,...,-1.174279,-2.629920,-2.771063,-2.191754,5.0,0.471946,-0.629404,-0.677108,-0.278189,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,HD8_HD223,OC(=O)CC1C(C(=C)/C=C/CC)=CC=C(C=1)O,C=C(/C=C/CC)c1ccc(O)cc1CC(=O)O,smHD8_HighDiv,C14H16O3,3.24,-3.76,-3.68,-3.74,-0.221176,...,1.920931,2.016149,1.991882,1.976321,618.0,1.876307,1.993038,1.922135,1.930493,612.0
618,HD8_DL089,OC1C=CC(=CC=1[C@H](CN)C)Cl,C[C@@H](CN)c1cc(Cl)ccc1O,smHD8_Druglike,C9H12NOCl,3.70,-3.69,-3.70,-3.67,-0.307500,...,2.016378,1.988979,2.089369,2.031575,619.0,0.038562,0.012315,0.077593,0.042824,311.0
619,HD8_HD269,S[C@H](C(=O)C1=CC=CC=C1)C(=O)O,O=C(O)[C@H](S)C(=O)c1ccccc1,smHD8_HighDiv,C9H8O3S,3.13,-3.58,-3.64,-3.45,-0.275385,...,2.166367,2.070489,2.395757,2.210871,620.0,0.722268,0.623232,0.946828,0.764109,492.0
620,HD8_HD316,O[S@@](=O)C1=CC=CC(=C1)NC=C,C=CNc1cccc([S@](=O)O)c1,smHD8_HighDiv,C8H9NO2S,3.04,-3.60,-3.57,-3.46,-0.300000,...,2.139096,2.165584,2.381830,2.228837,621.0,0.198230,0.245901,0.453665,0.299265,377.0
621,HD8_HD311,N[C@@](CI)(C)C(=O)[O-],C[C@@](N)(CI)C(=O)O,smHD8_HighDiv,C4H7NO2I,3.06,-2.75,-2.47,-2.74,-0.343750,...,3.298095,3.659933,3.384556,3.447528,622.0,-0.733165,0.003331,-0.710367,-0.480067,184.0

Warning: Total number of columns (26) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
DB_filtrado.columns

Index(['ID_deNovo', 'SMILES', 'SMILES_curated', 'Database', 'Formula', 'pKd',
       'Scores_Rep1', 'Scores_Rep2', 'Scores_Rep3', 'LE_Rep1', 'LE_Rep2',
       'LE_Rep3', 'Z_Rep1', 'Z_Rep2', 'Z_Rep3', 'Z_Score_Combined',
       'R_Z_Score', 'Z_Rep1_LE', 'Z_Rep2_LE', 'Z_Rep3_LE',
       'Z_Score_Combined_LE', 'R_Z_Score_LE'],
      dtype='object')

In [ ]:
# Normalize to a value between 0 and 1
DB_filtrado['Z_S_norm'] = (DB_filtrado['Z_Score_Combined'] - DB_filtrado['Z_Score_Combined'].min()) / (DB_filtrado['Z_Score_Combined'].max() - DB_filtrado['Z_Score_Combined'].min())
DB_filtrado['Z_LE_norm'] = (DB_filtrado['Z_Score_Combined_LE'] - DB_filtrado['Z_Score_Combined_LE'].min()) / (DB_filtrado['Z_Score_Combined_LE'].max() - DB_filtrado['Z_Score_Combined_LE'].min())
DB_filtrado['pKd_norm'] = (DB_filtrado['pKd'] - DB_filtrado['pKd'].min()) / (DB_filtrado['pKd'].max() - DB_filtrado['pKd'].min())

# Average of standardized scores
DB_filtrado['Z_combined_mean'] = (
    DB_filtrado['Z_S_norm'] +
    DB_filtrado['Z_LE_norm'] +
    (1 - DB_filtrado['pKd_norm'])  # We invest to ensure that smaller remains better
) / 3

# Top 5 by combined metric
top_5_combined_describe = DB_filtrado.nsmallest(5, 'Z_combined_mean')
top_5_Z_combined = top_5_combined_describe[['ID_deNovo', 'SMILES_curated', 'Database', 'pKd', 'Z_Score_Combined', 'Z_Score_Combined_LE','Z_S_norm', 'Z_LE_norm', 'pKd_norm', 'Z_combined_mean']]

In [ ]:
# Select columns
SCORE_combined = DB_filtrado[['ID_deNovo', 'SMILES_curated', 'Database', 'pKd', 'Z_Score_Combined', 'Z_Score_Combined_LE','Z_S_norm', 'Z_LE_norm', 'pKd_norm', 'Z_combined_mean']]
SCORE_combined

,ID_deNovo,SMILES_curated,Database,pKd,Z_Score_Combined,Z_Score_Combined_LE,Z_S_norm,Z_LE_norm,pKd_norm,Z_combined_mean
0,HD8_HD048,Oc1ccc(-c2[nH]ncc2Cl)cc1SCc1n[nH]c(=S)[nH]1,smHD8_HighDiv,3.78,-3.306968,-1.105339,0.000000,0.343006,0.326360,0.338882
1,HD8_DL038,O=C(O[C@@H](c1cc[nH]n1)c1nnc[nH]1)c1ccc(O)cc1,smHD8_Druglike,4.04,-2.824399,-0.749309,0.071444,0.406407,0.435146,0.347568
2,HD8_HD043,C=C(/C=C/c1[nH]cnc1-c1cn[nH]n1)c1ccc(O)cc1,smHD8_HighDiv,3.79,-2.545460,-0.541599,0.112741,0.443395,0.330544,0.408531
3,HD8_HD271,N/C(=C\c1[nH]ncc1Cl)C(N)(N)/C=C/[N+](=O)[O-],smHD8_HighDiv,3.13,-2.228566,-1.937926,0.159657,0.194742,0.054393,0.433335
4,HD8_DL072,NCCCNc1ccnc(CCc2nnc(C(=O)O)[nH]2)n1,smHD8_Druglike,3.80,-2.191754,-0.278189,0.165107,0.490303,0.334728,0.440227
...,...,...,...,...,...,...,...,...,...,...
617,HD8_HD223,C=C(/C=C/CC)c1ccc(O)cc1CC(=O)O,smHD8_HighDiv,3.24,1.976321,1.930493,0.782188,0.883618,0.100418,0.855129
618,HD8_DL089,C[C@@H](CN)c1cc(Cl)ccc1O,smHD8_Druglike,3.70,2.031575,0.042824,0.790369,0.547468,0.292887,0.681650
619,HD8_HD269,O=C(O)[C@H](S)C(=O)c1ccccc1,smHD8_HighDiv,3.13,2.210871,0.764109,0.816913,0.675912,0.054393,0.812811
620,HD8_HD316,C=CNc1cccc([S@](=O)O)c1,smHD8_HighDiv,3.04,2.228837,0.299265,0.819573,0.593134,0.016736,0.798657
621,HD8_HD311,C[C@@](N)(CI)C(=O)O,smHD8_HighDiv,3.06,3.447528,-0.480067,1.000000,0.454353,0.025105,0.809749

In [ ]:
#Save
top_5_combined_describe.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/top_5_combined_ConsensoReps_Zscore.csv", index=False)
top_5_Z_combined.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/top_5_Z_LE_ConsensoReps_Zscore.csv", index=False)
SCORE_combined.to_csv("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/DB_CONSENSO_Zscore_combined.csv", index=False)

In [ ]:
#Plot
import matplotlib.pyplot as plt

# Create a unique color for each database
categorias = DB_filtrado['Database'].unique()
colormap = plt.cm.get_cmap('Set3', len(categorias))
#color_dict = {cat: colormap(i) for i, cat in enumerate(categorias)}
color_dict = {
    "smHD8_Druglike": "#73d2dd",
    "smHD8_HighDiv": "#b57edc",
    "Lig_NF2889": "navy"

}

plt.figure(figsize=(10, 8), dpi=1000)

# ================================
# 1. General plot colored by Database
# ================================
for cat in categorias:
    df_cat = df_final[df_final['Database'] == cat]

    #  Define a custom bookmark
    marker_style = 's' if cat == 'Lig_NF2889' else 'o'

    plt.scatter(
        df_cat['Z_Score_Combined'],
        df_cat['Z_Score_Combined_LE'],
        s=50, alpha=0.7,
        color=color_dict[cat],
        edgecolors='black',
        linewidths=0.3,
        label=cat,
        marker=marker_style
    )

# ================================
# 2. Highlight Top 5
# ================================
plt.scatter(
    top_5_combined_describe['Z_Score_Combined'],
    top_5_combined_describe['Z_Score_Combined_LE'],
    s=20, color='red', label='Top 5', marker='*'
)

# Plot settings
#plt.title('Distribución de Z-Scores de acoplamiento molecular a sitio alostérico smHDAC8', fontsize=18)
plt.xlabel('Z-Score S', fontsize=16)
plt.ylabel('Z-Score LE', fontsize=16)

# Axis number size
plt.tick_params(axis='both', which='major', labelsize=14)

# Axis limits
plt.xlim(-4, 4)
plt.ylim(-4, 4)

# Legend aligned to the right
plt.legend(loc='lower center', bbox_to_anchor=(0.5, -0.25), ncol=3, fontsize=10)

plt.grid(True, linestyle='--', alpha=0.3)
plt.tight_layout()
plt.savefig("/content/drive/MyDrive/FBDD_Denovo_VRC/Dock_DeNovo_smHDAC8/Concatenar/Distribución_Z-Scores.png", dpi=600)

plt.show()